last_names = [
    "Vorrik", "Sorn", "Kael", "Draven", "Tarn", "Voss", "Revik", "Sorrel", "Korran", "Velth",
    "Myrek", "Dralos", "Zeroth", "Krynn", "Vosar", "Marek", "Vendra", "Threx", "Soral", "Brennik",
    "Korvan", "Ryvek", "Jurn", "Valen", "Syros", "Andor", "Aniseya", "Antilles", "Antilles", "Aphra", "Azadi", "Baba", "Bane",
    "Bendu", "Beq", "Bibble", "Billaba", "Binks", "Bliss", "Bonteri", "Bossk", "Caleen", "Calrissian", "Celchu", "Scaleback", "Clovis",
    "Cody", "Connix", "Cordova", "Dan", "Dameron", "Darklighter", "Dengar", "Djarin", "Divo", "Dod",
    "Dodonna", "Dooku", "Drallig", "Dume", "Jarrus", "Dune", "Durant", "Durith", "Elsbeth", "Embo", "Erso", "Estree", "Evazan",
    "Fandar", "Farr", "Fett", "Finn", "Fisto", "Fortuna", "Frik", "Fwip", "Gallia", "Gargan", "Garindan", "Genoa",
    "Gerrera", "Gideon", "Greez", "Grun", "Greedo", "Grogu", "Haako", "Hati", "Hemlock", "Hess", "Holdo", "Hux", "Jettster",
    "Jerjerrod", "Junda", "Kallus", "Kanata", "Karga", "Karn", "Karr", "kaz", "Kenobi", "Kestis", "Kolar", "Koon",
    "Koril", "Koth", "Krell", "Krennic", "Kryze", "Lars", "Lon", "Loy", "Merick", "Madine", "Malbus", "Malicos",
    "Mando", "Marek", "Maw", "Maz", "Marki", "Martez", "Mayfield", "Mattin", "Meero", "Melshi", "Mothma", "Motti",
    "Motto", "Mundi", "Nass", "Nawood", "Neel", "Nest", "Needa", "Nu", "Nunb", "Offee", "Ohnaka", "Organa", "Onyo", "Oola",
    "Orrelios", "Panaka", "Pellaeon", "Papanoida", "Pershing", "Phasma", "Piell", "Piett", "Plutt", "Poof", "Porkins", "Pryce",
    "Pryde", "Pyke", "Quarrie", "Jinn", "Raddus", "Rael", "Rakish", "Ralter", "Rampart", "Rancisis", "Ree", "Revan", "Rex",
    "Rau", "Rebo", "Reeves", "Skywalker", "Ri", "Roken", "Rook", "Rukh", "Rwoh", "Ryvora", "Sartha", "Sato", "Saxon", "Se", "Secura",
    "Senesca", "Sevander", "Shand", "Sinube", "Skoll", "Snootles", "Sol", "Solo", "Su", "Suduri", "Syndulla", "Taa", "Taggi", "Talzin",
    "Tambor", "Tano", "Tarpals", "Tapal", "Tekka", "Teva", "Ti", "Too", "Typho", "Unduli", "Valorum", "Vanth", "Veers",
    "Ventress", "Versio", "Vizago", "Vizsla", "Vos", "Vozo", "Warrick" "We", "Wesell", "Wexley", "Windu", "Wren", "Xiono",
    "Yaddle", "Yularen"
]
